[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn --config gunicorn.conf.py app:app"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.web]
processes = ["web: gunicorn --config gunicorn.conf.py app:app"]